name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker build --tag mbta_mapper .
    - run: docker tag mbta_mapper tandyy/mbta_mapper:latest
    - run: docker push tandyy/mbta_mapper:latest
